name: Oracle Connect Testing
on:
  push:
    branches: main
  
jobs:
  OracleConnectTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
        
      - name: Compile
        run: |
          cd $GITHUB_WORKSPACE
          export CLASSPATH="./ojdbc8.jar:./"
          echo "$env:LOGIN"
          java OracleCon.java ${{ secrets.LOGIN }} ${{ secrets.PASSWORD }}
