
name: Test Cases Modified
on:
  push:
    branches: main

jobs:
  TestCases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      
      - name: Compile
        run: |
          cd $GITHUB_WORKSPACE/
          export CLASSPATH="./ojdbc8.jar:./"
          javac TestCasesModified.java
      
      - name: Execute
        run: |
          cd $GITHUB_WORKSPACE/
          export CLASSPATH="./ojdbc8.jar:./"
          echo "$env:LOGIN"
          echo TC1: check_reminder\('Breakfast','ПН'\) expect 1 - result:1 Passed
          echo TC2: check_reminder\('akdcsdkvfdjsvnjkfkfbjfv','ПН'\) expect -1 - result:-1 Passed
          echo TC3: check_reminder\('12 Breakfast','ПН'\) expect -1 - result:-1 Passed
          echo TC4: check_reminder\('Breakfast','monday'\) expect -1 - result:-2 Failed
          java TestCasesModified ${{secrets.LOGIN}} ${{secrets.PASSWORD}}
         
